In [23]:
import pandas as pd
import re
import numpy as np

In [24]:
df = pd.read_json('data.jl', lines=True)
df = df.drop_duplicates('url')
df=df.dropna()
df.head(3)

,url,description,imame_urls,location,Price,Miscellaneous
0,https://www.airbnb.com/rooms/18477502?search_m...,About this spaceSituated in one of Seattle's f...,[https://a0.muscache.com/im/pictures/miso/Host...,"Entire townhouse in Seattle, Washington, Unite...",102699,10 guests · · · 5 bedrooms · · · 5 beds · ...
1,https://www.airbnb.com/rooms/37654064?search_m...,About this spaceMidcentury modern 2bed/2bath s...,[https://a0.muscache.com/im/pictures/7b57bf26-...,"Entire home in Los Angeles, California, United...",208528,6 guests · · · 2 bedrooms · · · 3 beds · ...
2,https://www.airbnb.com/rooms/53132475?search_m...,About this spaceWelcome to UNTITLED at 3 Freem...,[https://a0.muscache.com/im/pictures/abb9360d-...,"Room in hotel in New York, United States",16264,2 guests · · · 1 bedroom · · · 1 bed · · ...

In [25]:
df.info()

<class 'pandas.DataFrame'>
Index: 2272 entries, 0 to 2429
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   url            2272 non-null   str
 1   description    2272 non-null   str
 2   imame_urls     2272 non-null   object
 3   location       2272 non-null   str
 4   Price          2272 non-null   object
 5   Miscellaneous  2272 non-null   str
dtypes: object(2), str(4)
memory usage: 124.2+ KB

In [26]:
df['imame_urls'] = df['imame_urls'].apply(lambda x: x[0] if len(x)>0 else None)

In [27]:
df.info()

<class 'pandas.DataFrame'>
Index: 2272 entries, 0 to 2429
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   url            2272 non-null   str
 1   description    2272 non-null   str
 2   imame_urls     2269 non-null   str
 3   location       2272 non-null   str
 4   Price          2272 non-null   object
 5   Miscellaneous  2272 non-null   str
dtypes: object(1), str(5)
memory usage: 124.2+ KB

In [28]:
df = df.dropna()

In [29]:
df.info()

<class 'pandas.DataFrame'>
Index: 2269 entries, 0 to 2429
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   url            2269 non-null   str
 1   description    2269 non-null   str
 2   imame_urls     2269 non-null   str
 3   location       2269 non-null   str
 4   Price          2269 non-null   object
 5   Miscellaneous  2269 non-null   str
dtypes: object(1), str(5)
memory usage: 124.1+ KB

In [30]:
df.head(3)

,url,description,imame_urls,location,Price,Miscellaneous
0,https://www.airbnb.com/rooms/18477502?search_m...,About this spaceSituated in one of Seattle's f...,https://a0.muscache.com/im/pictures/miso/Hosti...,"Entire townhouse in Seattle, Washington, Unite...",102699,10 guests · · · 5 bedrooms · · · 5 beds · ...
1,https://www.airbnb.com/rooms/37654064?search_m...,About this spaceMidcentury modern 2bed/2bath s...,https://a0.muscache.com/im/pictures/7b57bf26-b...,"Entire home in Los Angeles, California, United...",208528,6 guests · · · 2 bedrooms · · · 3 beds · ...
2,https://www.airbnb.com/rooms/53132475?search_m...,About this spaceWelcome to UNTITLED at 3 Freem...,https://a0.muscache.com/im/pictures/abb9360d-b...,"Room in hotel in New York, United States",16264,2 guests · · · 1 bedroom · · · 1 bed · · ...

In [31]:
df['description'] = df['description'].str.replace('About this space', '')
df['description'] = np.where(df['description'].apply(lambda x: len(x)) > 0, df['description'], np.nan)
df.head(3)

,url,description,imame_urls,location,Price,Miscellaneous
0,https://www.airbnb.com/rooms/18477502?search_m...,Situated in one of Seattle's friendliest and f...,https://a0.muscache.com/im/pictures/miso/Hosti...,"Entire townhouse in Seattle, Washington, Unite...",102699,10 guests · · · 5 bedrooms · · · 5 beds · ...
1,https://www.airbnb.com/rooms/37654064?search_m...,Midcentury modern 2bed/2bath stilt home with s...,https://a0.muscache.com/im/pictures/7b57bf26-b...,"Entire home in Los Angeles, California, United...",208528,6 guests · · · 2 bedrooms · · · 3 beds · ...
2,https://www.airbnb.com/rooms/53132475?search_m...,Welcome to UNTITLED at 3 Freeman Alley!Our Stu...,https://a0.muscache.com/im/pictures/abb9360d-b...,"Room in hotel in New York, United States",16264,2 guests · · · 1 bedroom · · · 1 bed · · ...

In [32]:
def extract_city(location):
    if not isinstance(location, str):
        return None
    parts = re.split(r'\s+in\s+', location, flags=re.IGNORECASE)
    if len(parts) < 2:
        return None
    city = parts[-1].split(',')[0].strip()
    return city

In [33]:
df['city'] = df['location'].apply(extract_city)
df.head(6)

,url,description,imame_urls,location,Price,Miscellaneous,city
0,https://www.airbnb.com/rooms/18477502?search_m...,Situated in one of Seattle's friendliest and f...,https://a0.muscache.com/im/pictures/miso/Hosti...,"Entire townhouse in Seattle, Washington, Unite...",102699,10 guests · · · 5 bedrooms · · · 5 beds · ...,Seattle
1,https://www.airbnb.com/rooms/37654064?search_m...,Midcentury modern 2bed/2bath stilt home with s...,https://a0.muscache.com/im/pictures/7b57bf26-b...,"Entire home in Los Angeles, California, United...",208528,6 guests · · · 2 bedrooms · · · 3 beds · ...,Los Angeles
2,https://www.airbnb.com/rooms/53132475?search_m...,Welcome to UNTITLED at 3 Freeman Alley!Our Stu...,https://a0.muscache.com/im/pictures/abb9360d-b...,"Room in hotel in New York, United States",16264,2 guests · · · 1 bedroom · · · 1 bed · · ...,New York
3,https://www.airbnb.com/rooms/54350076?search_m...,Welcome to Piseco Lake House! Enjoy an authent...,https://a0.muscache.com/im/pictures/miso/Hosti...,"Entire home in Piseco, New York, United States",165885,6 guests · · · 3 bedrooms · · · 4 beds · ...,Piseco
4,https://www.airbnb.com/rooms/11226038143094433...,Kick back in this peaceful room with an en-sui...,https://a0.muscache.com/im/pictures/hosting/Ho...,"Private room in home in San Francisco, Califor...",70478,2 guests · · · 1 bedroom · · · 1 bed · · ...,San Francisco
5,https://www.airbnb.com/rooms/16174863011703687...,Love Lake Life all year long. Bring friends an...,https://a0.muscache.com/im/pictures/hosting/Ho...,"Entire home in Port Clinton, Ohio, United States",2,8 guests · · · 3 bedrooms · · · 6 beds · ...,Port Clinton

In [34]:
df.iloc[10, -2].split(' ·  ·  · ')

['1 bed', 'Shared bathroom']

In [35]:
def numerical_features(misc: str) -> list:
  guests = beds = baths = bedrooms = lux = 0
  
  misc_list = [s for s in misc.split(' ·  ·  · ') if s.strip()]
  patterns = [
    (r'(\d+(?:\.\d+)?)(?:\+)?\s*guests?', 'guests'),   
    (r'(\d+(?:\.\d+)?)\s*(?:bedroom|bedrooms)', 'bedrooms'),
    (r'(\d+(?:\.\d+)?)\s*(?:bed|beds)\b', 'beds'),       
    (r'(\d+(?:\.\d+)?)\s*(?:bath|baths|bathroom|bathrooms)', 'baths'),
    ]
  
  for string in misc_list:
    c=0
    for pattern, var in patterns:
      match = re.search(pattern, string, flags=re.IGNORECASE)
      if match:
        num = float(match.group(1))
        if var == 'guests':
          guests = num
        elif var == 'beds':
          beds = num
        elif var == 'bedrooms':
          bedrooms = num
        elif var == 'baths':
          baths = num
      else:
        c+=1
    if c >=4:
      lux+=1
  return guests, bedrooms, beds, baths, lux

In [36]:
df[['guests', 'bedrooms', 'beds', 'baths', 'luxury_items']] = df['Miscellaneous'].apply( lambda x: pd.Series(numerical_features(x)))
df.head(6)

,url,description,imame_urls,location,Price,Miscellaneous,city,guests,bedrooms,beds,baths,luxury_items
0,https://www.airbnb.com/rooms/18477502?search_m...,Situated in one of Seattle's friendliest and f...,https://a0.muscache.com/im/pictures/miso/Hosti...,"Entire townhouse in Seattle, Washington, Unite...",102699,10 guests · · · 5 bedrooms · · · 5 beds · ...,Seattle,10.0,5.0,5.0,3.5,0.0
1,https://www.airbnb.com/rooms/37654064?search_m...,Midcentury modern 2bed/2bath stilt home with s...,https://a0.muscache.com/im/pictures/7b57bf26-b...,"Entire home in Los Angeles, California, United...",208528,6 guests · · · 2 bedrooms · · · 3 beds · ...,Los Angeles,6.0,2.0,3.0,2.0,0.0
2,https://www.airbnb.com/rooms/53132475?search_m...,Welcome to UNTITLED at 3 Freeman Alley!Our Stu...,https://a0.muscache.com/im/pictures/abb9360d-b...,"Room in hotel in New York, United States",16264,2 guests · · · 1 bedroom · · · 1 bed · · ...,New York,2.0,1.0,1.0,0.0,1.0
3,https://www.airbnb.com/rooms/54350076?search_m...,Welcome to Piseco Lake House! Enjoy an authent...,https://a0.muscache.com/im/pictures/miso/Hosti...,"Entire home in Piseco, New York, United States",165885,6 guests · · · 3 bedrooms · · · 4 beds · ...,Piseco,6.0,3.0,4.0,2.0,0.0
4,https://www.airbnb.com/rooms/11226038143094433...,Kick back in this peaceful room with an en-sui...,https://a0.muscache.com/im/pictures/hosting/Ho...,"Private room in home in San Francisco, Califor...",70478,2 guests · · · 1 bedroom · · · 1 bed · · ...,San Francisco,2.0,1.0,1.0,1.5,0.0
5,https://www.airbnb.com/rooms/16174863011703687...,Love Lake Life all year long. Bring friends an...,https://a0.muscache.com/im/pictures/hosting/Ho...,"Entire home in Port Clinton, Ohio, United States",2,8 guests · · · 3 bedrooms · · · 6 beds · ...,Port Clinton,8.0,3.0,6.0,2.0,0.0

In [37]:
output_df = df.loc[:, ['url', 'description', 'imame_urls', 'city', 'guests', 'bedrooms', 'beds', 'baths', 'luxury_items', 'Price']]
output_df.columns = ['url', 'description', 'image', 'city', 'guests', 'bedrooms', 'beds', 'baths', 'luxury_items', 'Price']
output_df

,url,description,image,city,guests,bedrooms,beds,baths,luxury_items,Price
0,https://www.airbnb.com/rooms/18477502?search_m...,Situated in one of Seattle's friendliest and f...,https://a0.muscache.com/im/pictures/miso/Hosti...,Seattle,10.0,5.0,5.0,3.5,0.0,102699
1,https://www.airbnb.com/rooms/37654064?search_m...,Midcentury modern 2bed/2bath stilt home with s...,https://a0.muscache.com/im/pictures/7b57bf26-b...,Los Angeles,6.0,2.0,3.0,2.0,0.0,208528
2,https://www.airbnb.com/rooms/53132475?search_m...,Welcome to UNTITLED at 3 Freeman Alley!Our Stu...,https://a0.muscache.com/im/pictures/abb9360d-b...,New York,2.0,1.0,1.0,0.0,1.0,16264
3,https://www.airbnb.com/rooms/54350076?search_m...,Welcome to Piseco Lake House! Enjoy an authent...,https://a0.muscache.com/im/pictures/miso/Hosti...,Piseco,6.0,3.0,4.0,2.0,0.0,165885
4,https://www.airbnb.com/rooms/11226038143094433...,Kick back in this peaceful room with an en-sui...,https://a0.muscache.com/im/pictures/hosting/Ho...,San Francisco,2.0,1.0,1.0,1.5,0.0,70478
...,...,...,...,...,...,...,...,...,...,...
2425,https://www.airbnb.com/rooms/15017864625021474...,Wake up to sea breezes and the charm of a coas...,https://a0.muscache.com/im/pictures/hosting/Ho...,Quincy,8.0,4.0,5.0,2.0,0.0,148560
2426,https://www.airbnb.com/rooms/94783011387687528...,"This special place is close to everything, loc...",https://a0.muscache.com/im/pictures/miso/Hosti...,Boston,2.0,0.0,1.0,1.0,1.0,66435
2427,https://www.airbnb.com/rooms/15786270476553229...,Moody Blues in Music City is newly furnished!S...,https://a0.muscache.com/im/pictures/hosting/Ho...,Nashville,6.0,1.0,4.0,1.0,0.0,95358
2428,https://www.airbnb.com/rooms/14623681409198487...,"Explore a beautifully reimagined luxury hotel,...",https://a0.muscache.com/im/pictures/prohost-ap...,Boston,2.0,1.0,1.0,0.0,1.0,143942
2429,https://www.airbnb.com/rooms/16008808404137474...,"Peaceful Retreat | Close to Broadway, City Vie...",https://a0.muscache.com/im/pictures/hosting/Ho...,Nashville,6.0,1.0,1.0,1.0,0.0,61223

In [38]:
output_df.info()

<class 'pandas.DataFrame'>
Index: 2269 entries, 0 to 2429
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   url           2269 non-null   str
 1   description   2267 non-null   str
 2   image         2269 non-null   str
 3   city          2269 non-null   str
 4   guests        2269 non-null   float64
 5   bedrooms      2269 non-null   float64
 6   beds          2269 non-null   float64
 7   baths         2269 non-null   float64
 8   luxury_items  2269 non-null   float64
 9   Price         2269 non-null   object
dtypes: float64(5), object(1), str(4)
memory usage: 195.0+ KB

In [39]:
output_df['Price'] = np.where((output_df['Price'] == '₽RUB'), np.nan, output_df['Price'])

In [40]:
output_df['Price'] = output_df['Price'].astype(float, errors='ignore')
output_df['Price'] = np.where((output_df['Price'] < 1000), np.nan, output_df['Price'])

In [41]:
output_df = output_df.dropna()

In [42]:
output_df.info()

<class 'pandas.DataFrame'>
Index: 2111 entries, 0 to 2429
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   url           2111 non-null   str
 1   description   2111 non-null   str
 2   image         2111 non-null   str
 3   city          2111 non-null   str
 4   guests        2111 non-null   float64
 5   bedrooms      2111 non-null   float64
 6   beds          2111 non-null   float64
 7   baths         2111 non-null   float64
 8   luxury_items  2111 non-null   float64
 9   Price         2111 non-null   float64
dtypes: float64(6), str(4)
memory usage: 181.4 KB

In [43]:
output_df['s3_url'] = [f"http://localhost:9000/airbnb-images/image_{i+1}.jpg" for i in range(len(output_df))]

In [44]:
output_df.to_excel('dataset.xlsx', index=False)

In [45]:
output_df.info()

<class 'pandas.DataFrame'>
Index: 2111 entries, 0 to 2429
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   url           2111 non-null   str
 1   description   2111 non-null   str
 2   image         2111 non-null   str
 3   city          2111 non-null   str
 4   guests        2111 non-null   float64
 5   bedrooms      2111 non-null   float64
 6   beds          2111 non-null   float64
 7   baths         2111 non-null   float64
 8   luxury_items  2111 non-null   float64
 9   Price         2111 non-null   float64
 10  s3_url        2111 non-null   str
dtypes: float64(6), str(5)
memory usage: 197.9 KB